#
#
#

get:
  summary: Product Data
  description: Product, a Container for one or more Lot objects.
  tags:
    - Config
  parameters:
    - name: q
      in: query
      required: false
      schema:
        type: string
      description: Search Term.
  responses:
    '200':
      description: An array of Product objects
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schema/Product'
    '400':
      $ref: '#/components/schema/Error400'
    '403':
      $ref: '#/components/schema/Error403'
    '500':
      $ref: '#/components/schema/Error500'
