#
#
#


get:
  operationId: productView
  summary: Product Data
  description: Product defines attributes of an Inventory Lot such as Weight/Volume, Package Size
  tags:
    - Config
  parameters:
    - name: id
      description: Unique ULID value for this Product
      in: path
      required: true
      schema:
        type: string
  responses:
    '200':
      description: A Product Object
      content:
        application/json:
          schema:
            $ref: '#/components/schema/Product'
    '400':
      $ref: '#/components/schema/Error400'
    '403':
      $ref: '#/components/schema/Error403'
    '500':
      $ref: '#/components/schema/Error500'
