#
# /company
#

get:
  operationId: companySearch
  summary: Search Company Data
  description: Company, top level grouping of a business
  tags:
    - Config
  parameters:
    - name: q
      in: query
      description: Search Term.
      required: false
      schema:
          type: string
  responses:
    '200':
      description: An array of Company objects
      content:
          application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/Company'
    '400':
      $ref: '#/components/Error400'
    '403':
      $ref: '#/components/Error403'
    '500':
      $ref: '#/components/Error500'
