#
# /license
#

get:
  operationId: licenseSearch
  summary: License Data
  description: License, attached to a Company
  tags:
    - Config
  responses:
    '200':
      description: An array of License objects
      schema:
        type: array
        items:
          $ref: '#/components/License'
    '400':
      $ref: '#/components/Error400'
    '403':
      $ref: '#/components/Error403'
    '500':
      $ref: '#/components/Error500'
