#
# Get a Specific License
#

get:
  operationId: licenseView
  summary: License
  description: A Company contains one or more License objects
  tags:
    - Config
  parameters:
    - name: code
      in: path
      required: true
      schema:
        type: string
      description: "The ID of the License"
  responses:
    '200':
      description: A License
      application/json:
        schema:
          $ref: '#/components/schema/License'
    '500':
      $ref: '#/components/schema/Error500'
