#
# OpenTHC API
#
# Have to do manual work to split to smaller files :(
# http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html
#

openapi: 3.0.0

info:
  $ref: './info.yaml'

externalDocs:
  description: "Find out more about OpenTHC"
  url: "https://openthc.org"


#
# Servers
servers:
  - url: https://api.openthc.org/v2016
    description: Example Reference
  - url: https://YOUR_SERVER/some/path
    description: You can install to sub-host or sub-path


consumes:
  - application/json
  - multipart/form-data

produces:
  - application/json


#
# Paths
paths:
  $ref: './paths/_.yaml'




#
#models:
#  $ref: './models.yaml'

#
#
#components:
#  schemas:
#  responses:
#  parameters:
#  examples:
#  requestBodies:
#  headers:
#  securitySchemes:
#  links:
#  callbacks:
#  $ref: './components.yaml'

#
# Object Definitions (our made up name?)
definitions:
  $ref: 'definitions/_.yaml'
