#
# OpenTHC API
#

openapi: 3.0.2

info:
  $ref: './info.yaml'

externalDocs:
  description: "Find out more about OpenTHC"
  url: "https://openthc.org"


#
# Servers
servers:
  - url: https://YOUR_SERVER/YOUR/PATH
    description: You can install to sub-host or sub-path
  - url: https://api.openthc.org/v2016
    description: Example Reference
  - url: https://cre.openthc.dev
    description: Example Implementation

tags:
  - name: Authentication
    description: Authentication and session management
  - name: Config
    description: Configuration options for Company, License and other core objects
  - name: Lab
    description: Details about the Quality Assurance data, Laboratory results


#
# Paths
paths:
  $ref: './paths/_.yaml'

#
#models:
#  $ref: './models.yaml'

#
#
components:
  schema:
    $ref: 'components/schema.yaml'
#  responses:
#    $ref: 'components/responses.yaml'
#  parameters:
#  examples:
#  requestBodies:
#  headers:
#  securitySchemes:
#  links:
#  callbacks:
#  $ref: './components.yaml'
