#
# OpenTHC API
#

openapi: 3.0.2

info:
  $ref: './info.yaml'

externalDocs:
  description: "Find out more about OpenTHC"
  url: "https://openthc.org"


#
# Servers
servers:
  - url: https://api.openthc.org/v2016
    description: Example Reference
  - url: https://YOUR_SERVER/some/path
    description: You can install to sub-host or sub-path

tags:
  - name: Authentication
    description: Authentication and session management
  - name: Config
    description: Configuration options for Company, License and other core objects
  - name: QA
    description: Details about the Quality Assurance data, Laboratory results


#
# Paths
paths:
  $ref: './paths/_.yaml'

#
#models:
#  $ref: './models.yaml'

#
#
components:
  schemas:
    $ref: 'components/_.yaml'
#  schemas:
#  responses:
#  parameters:
#  examples:
#  requestBodies:
#  headers:
#  securitySchemes:
#  links:
#  callbacks:
#  $ref: './components.yaml'
