#
#
#

get:
  operationId: productList
  summary: Product Data
  description: Product, a Container for one or more Lot objects.
  tags:
    - Config
  parameters:
    - name: q
      in: query
      description: Search Term.
      required: false
      type: string
  responses:
    200:
      description: An array of Product objects
      schema:
        type: array
        items:
          $ref: '#/definitions/Product'
    400:
      $ref: '#/definitions/Error400'
    403:
      $ref: '#/definitions/Error403'
    500:
      $ref: '#/definitions/Error500'
