#
#
#


get:
  operationId: productView
  summary: Product Data
  description: Company, top level grouping of a business
  tags:
    - Config
  parameters:
    - name: code
      description: The Plant Hash Code
      in: path
      required: true
      schema:
        type: string
  responses:
    '200':
      description: A Product Object
      content:
        application/json:
          schema:
            $ref: '#/components/Product'
    '400':
      $ref: '#/components/Error400'
    '403':
      $ref: '#/components/Error403'
    '500':
      $ref: '#/components/Error500'
