#
#
#


get:
  operationId: productView
  summary: Product Data
  description: Company, top level grouping of a business
  tags:
    - Config
  parameters:
    - name: code
      description: The Plant Hash Code
      in: path
      type: string
      required: true
  responses:
    200:
      description: A Product Object
      schema:
        $ref: '#/definitions/Product'
    400:
      $ref: '#/definitions/Error400'
    403:
      $ref: '#/definitions/Error403'
    500:
      $ref: '#/definitions/Error500'
