#
# Get a Specific Contact
#

get:
  operationId: contactView
  summary: Contacts
  description: Contacts are members of a Company
  tags:
    - Config
  parameters:
    - name: code
      in: path
      required: true
      schema:
        type: string
      description: "The ID of the Contact"
  responses:
    '200':
      description: A Contact
      content:
        application/json:
          schema:
            $ref: '#/components/Contact'
    '500':
      $ref: '#/components/Error500'
