#
# /contact
#

get:
  operationId: contactSearch
  summary: Contacts
  description: Contacts are members of a Company
  tags:
    - Config
  parameters:
    - name: email
      in: query
      type: string
      required: true
      description: "The Email"
    - name: phone
      in: query
      type: string
      required: true
      description: "The Email"
  responses:
    '200':
      description: An array of Contacts
      schema:
        type: array
        items:
          $ref: '#/definitions/Contact'
    '400':
      $ref: '#/definitions/Error400'
    '403':
      $ref: '#/definitions/Error403'
    '500':
      $ref: '#/definitions/Error500'
