#
# /contact
#

get:
  operationId: contactSearch
  summary: Contacts
  description: Contacts are members of a Company
  tags:
    - Config
  parameters:
    - name: email
      in: query
      required: true
      schema:
        type: string
      description: "The Email"
    - name: phone
      in: query
      required: true
      schema:
        type: string
      description: "The Email"
  responses:
    '200':
      description: An array of Contacts
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/Contact'
    '400':
      $ref: '#/components/Error400'
    '403':
      $ref: '#/components/Error403'
    '500':
      $ref: '#/components/Error500'
