#
# Common Components
#

Response_General:
  description: "A General Response"
  type: object
  properties:
    data:
      description: "Some kind of data, an array of objects or a single object"
    meta:
      description: "Additional Helpful info, generally an object or array of objects"


Response_Failure:
  description: "A Failure Type Response"
  type: object
  description: "General Failure Error"
  properties:
    data:
      type: object
      description: Usually NULL but main contain information about the underlying data
    meta:
      type: object
      description: Meta may contain some details about the error


#
# Account Object?
#Account:
#  type: object
#  properties:
#    code:
#      type: string
#      description: Code of the Account, could be a license or business identifier
#    name:
#      type: string
#      description: Name of the Account.

#
# Company Object
Company:
  $ref: './schema/Company.yaml'


#
#
Company_Type:
  $ref: './schema/Company_Type.yaml'


#
# License
License:
  $ref: './schema/License.yaml'

#
#
License_Type:
  $ref: './schema/License_Type.yaml'


# Contact Object
Contact:
  $ref: './schema/Contact.yaml'


#
#
Contact_Type:
  type: string
  enum:
    - Owner
    - User
    - Employee
    - Driver
    - Vendor
    - Client


#
# Plant Object
Plant:
  type: object
  properties:
    name:
      type: string
      description: Free-form Name of the plant, many times just the Strain
    strain:
      type: object
      $ref: '#/components/schemas/Strain'


#
# Plant_Collect Object
Plant_Collect:
  type: object
  properties:
    type:
      type: string
      enum: [ "raw", "net", "wet-plant", "wet-waste", "dry-buds", "dry-trim", "dry-waste" ]
      description: "Material Type: Flower/Wet, Flower/Dry, Trim/Wet|Dry, Waste/Wet|Dry"
    qty:
      type: number
      format: double
    uom:
      type: string
      enum: [ "g", "kg", "oz", "lb" ]
    # plant_list:
    #   type: array

#
# Inventory Object
Lot:
  type: object
  required: [ "id", "name", "product" ]
  properties:
    id:
      type: string
      description: The Inventory Unique Identifier
    name:
      type: string
    product:
      $ref: '#/components/schemas/Product'
    strain:
      $ref: '#/components/schemas/Strain'


#
#
# Package:
#   type: object
#   properties:
#     qty:
#       type: string
#     uom:
#       type: number

#
# A Product
Product:
  type: object
  properties:
    id:
      type: string
      description: The Product Unique Identifer from the CRE
    name:
      type: string
    type:
      $ref: '#/components/schemas/Product_Type'
    meta:
      type: object


#
# a product Type
Product_Type:
  $ref: './schema/Product_Type.yaml'


#
#
Lab_Metric:
  $ref: './schema/Lab_Metric.yaml'

#
#
Lab_Sample:
  $ref: './schema/Lab_Sample.yaml'


#
#
Lab_Result:
  $ref: './schema/Lab_Result.yaml'


#
#
Lab_Result_Metric:
  $ref: './schema/Lab_Result_Metric.yaml'


#
#
Transfer:
  type: object
  properties:
    kind:
      type: string
      enum: [ "incoming", "outgoing" ]
    source_license:
      type: string
    target_license:
      type: string
    depart:
      type: string
      format: dateTime
    arrive:
      type: string
      format: dateTime
    item_list:
      type: array
      items:
        $ref: '#/components/schemas/Transfer_Inventory'


#
#
Transfer_Inventory:
  type: object
  properties:
    inventory:
      type: string
      description: Inventory as String ID or Object
    price:
      type: number
      format: double
      description: The full price of the item


#
#
Sale:
  type: object
  properties:
    inventory:
      description: Inventory Item Identifier
      type: string
    unit_count:
      description: Quantity of Items Sold
      type: string
    unit_price:
      description: Price per Unit *NOT* the full price
      type: string
    created:
      type: string
      format: dateTime

Sale_Item:
  type: object


Strain:
  $ref: './schema/Strain.yaml'

#
#
Zone:
  type: object
  properties:
    id:
      type: string
      description: The ID
    name:
      type: string
      description: The Name


#
#
Request_Create_Lot:
  description: Create a New Lot
  type: object
  properties:
    source:
      type: null
    output:
      type: object
      properties:
        product_id:
          type: string
        qty:
          type: number

#
#
Request_Convert_Lot:
  description: Convert one or more Source lots to Output
  type: object
  properties:
    source:
      type: null
    output:
      type: object
      properties:
        product_id:
          type: string
        qty:
          type: number


#
#
Request_Split_Lot:
  description: Split some material from an original lot, creating a new sub-lot
  type: object
  properties:
    source:
      type: string
    output:
      type: number
