#
# Zone End Point
#

get:
  summary: "Get a LIst of all the Zones"
  tags:
    - Config
post:
  summary: "Create a Zone (aka: Area or Room)"
  tags:
    - Config
  requestBody:
    description: Zone Information
    required: true
    content:
      application/x-www-form-urlencoded:
        schema:
          type: object
          properties:
            id:
              description: Unique ULID value for this Zone
              in: path
              type: string
            name:
              description: "The Name for this Zone"
              in: formData
              type: string
            type:
              description: "The Type of Room: Plant or Inventory"
              in: formData
              type: string
            flag_quarantine:
              description: "If the Zone is a designated quarantine area"
              in: formData
              type: string
