post:
  summary: "Update a Zone (aka: Area or Room)"
  tags:
    - Config
  requestBody:
    description: Zone Information
    required: true
    content:
      application/x-www-form-urlencoded:
        schema:
          type: object
          properties:
            id:
              description: Unique ULID value for this Zone
              type: string
            name:
              description: "The Name for this Zone"
              type: string
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Zone'
